# Generated by Django 4.0.1 on 2022-05-05 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_news_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_events',
            name='pic',
        ),
    ]
