# Generated by Django 4.0.1 on 2022-05-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_remove_news_events_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_events',
            name='pic',
            field=models.ImageField(blank=True, default='-', null=True, upload_to='img', verbose_name='file'),
        ),
    ]
