# Generated by Django 4.0.1 on 2022-05-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_news_events_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='news_events',
            new_name='news',
        ),
    ]
