# Generated by Django 4.0.1 on 2022-05-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_rename_news_events_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.ImageField(blank=True, default='-', null=True, upload_to='img', verbose_name='file')),
            ],
        ),
    ]
