# Generated by Django 4.0.1 on 2022-05-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_career'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='career',
            new_name='careers',
        ),
    ]
