# Generated by Django 4.0.1 on 2022-05-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_application_forms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='application_forms',
        ),
    ]
