# Generated by Django 4.0.1 on 2022-05-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_delete_application_forms'),
    ]

    operations = [
        migrations.CreateModel(
            name='videogallery_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.TextField()),
            ],
        ),
    ]
