# Generated by Django 4.0.1 on 2022-05-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_videogallery_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='videogallery_link',
        ),
    ]
