# Generated by Django 4.0.1 on 2022-05-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_videogallery_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
