# Generated by Django 4.0.1 on 2022-05-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_news_tbl2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
