# Generated by Django 4.0.1 on 2022-05-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0025_news_tbl1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notifications',
        ),
    ]
