# Generated by Django 4.0.1 on 2022-05-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0026_delete_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('post_date', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, default='-', null=True, upload_to='img', verbose_name='file')),
            ],
        ),
    ]
