# Generated by Django 4.0.1 on 2022-05-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0028_institution_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='appliction_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='')),
                ('month_year', models.CharField(max_length=150)),
            ],
        ),
    ]
