# Generated by Django 4.0.1 on 2022-05-20 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0029_appliction_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliction_form',
            old_name='month_year',
            new_name='title',
        ),
    ]
